<a href="https://colab.research.google.com/github/kerekspinney/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [43]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
# from tensorflow.keras.models import Model
# from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [44]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [45]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df


Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [46]:
# Create a list of at least 10 column names to use as X data
column_list = attrition_df[['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime', 'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']]


# Create X_df using your selected columns
X_df = column_list

# Show the data types for X_df
X_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Education                1470 non-null   int64 
 1   Age                      1470 non-null   int64 
 2   DistanceFromHome         1470 non-null   int64 
 3   JobSatisfaction          1470 non-null   int64 
 4   OverTime                 1470 non-null   object
 5   StockOptionLevel         1470 non-null   int64 
 6   WorkLifeBalance          1470 non-null   int64 
 7   YearsAtCompany           1470 non-null   int64 
 8   YearsSinceLastPromotion  1470 non-null   int64 
 9   NumCompaniesWorked       1470 non-null   int64 
dtypes: int64(9), object(1)
memory usage: 115.0+ KB


In [47]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)


In [48]:
X_train['OverTime']

464      No
512      No
480      No
680      No
1023     No
       ... 
715     Yes
905      No
1096    Yes
235     Yes
1061     No
Name: OverTime, Length: 1102, dtype: object

In [49]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary - fittransform
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

overtime_encoder = LabelEncoder()



X_train['OverTime_Encoded'] = overtime_encoder.fit_transform(np.array(X_train['OverTime'])).reshape(-1,1)
X_test['OverTime_Encoded'] = overtime_encoder.fit_transform(np.array(X_test['OverTime'])).reshape(-1,1)

X_train['OverTime_Encoded'].shape

X_train.drop(columns=['OverTime'], inplace=True)
X_test.drop(columns=['OverTime'], inplace=True)



In [50]:
# Create a StandardScaler
import sklearn as skl
X_scaler = skl.preprocessing.StandardScaler()

# Fit the StandardScaler to the training data
X_scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


In [51]:
y_train['Attrition']

464      No
512      No
480     Yes
680      No
1023     No
       ... 
715      No
905      No
1096     No
235      No
1061     No
Name: Attrition, Length: 1102, dtype: object

In [52]:
y_train['Attrition']

464      No
512      No
480     Yes
680      No
1023     No
       ... 
715      No
905      No
1096     No
235      No
1061     No
Name: Attrition, Length: 1102, dtype: object

In [64]:
# Create a OneHotEncoder for the Attrition column
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output = False)

y_attrition_train = y_train['Attrition']
y_attrition_test = y_test['Attrition']

# Fit the encoder to the training data
y_attrition_train = ohe.fit_transform(np.array(y_train[['Attrition']]))


# Transform the training data
y_attrition_test = ohe.fit_transform(np.array(y_test[['Attrition']]))



y_attrition_train

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [65]:
# Create two new variables by applying the encoder
# to the training and testing data


y_department_train = y_train['Department']
y_department_test = y_test['Department']


#Encode the Department

y_department_train  = ohe.fit_transform(np.array(y_department_train).reshape(-1,1))
y_department_test = ohe.fit_transform(np.array(y_department_test).reshape(-1,1))

y_department_train






array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [66]:
y_attrition_train

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

## Create, Compile, and Train the Model

In [67]:
len(X_train.columns)

10

In [68]:
# Find the number of columns in the X training data
X_train.columns

# Create the input layer
input_layer = layers.Input(shape=(len(X_train.columns)), name='input_features')


# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(units=128, activation='relu')(shared_layer1)

In [69]:
# Create a branch for Department
# with a hidden layer and an output layer
Department_layer1 = layers.Dense(32, activation='softmax', name='Department_layer1')(shared_layer2)


# Create the output layer
Department_output = layers.Dense(3, activation='softmax', name='Department_output')(Department_layer1)


In [70]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_layer1 = layers.Dense(32, activation='softmax', name='attrition_layer1')(shared_layer2)


# Create the output layer
attrition_output = layers.Dense(2, activation='softmax', name='attrition_output')(attrition_layer1)


In [71]:
# Create the model
model = Model(inputs=input_layer, outputs=[Department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'Department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'},
              metrics={'Department_output': 'accuracy', 'attrition_output': 'accuracy'})


# Summarize the model
model.summary()


Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_features (InputLayer  [(None, 10)]                 0         []                            
 )                                                                                                
                                                                                                  
 dense_6 (Dense)             (None, 64)                   704       ['input_features[0][0]']      
                                                                                                  
 dense_7 (Dense)             (None, 128)                  8320      ['dense_6[0][0]']             
                                                                                                  
 Department_layer1 (Dense)   (None, 32)                   4128      ['dense_7[0][0]']       

In [72]:
#train the model.


model.fit(
    X_train, {'attrition_output' : y_attrition_train, 'Department_output' : y_department_train},
    epochs=10
)

Epoch 1/10
35/35 [==============================] - 2s 6ms/step - loss: 1.6982 - Department_output_loss: 1.0166 - attrition_output_loss: 0.6816 - Department_output_accuracy: 0.6525 - attrition_output_accuracy: 0.7060
Epoch 2/10
35/35 [==============================] - 0s 5ms/step - loss: 1.5813 - Department_output_loss: 0.9809 - attrition_output_loss: 0.6004 - Department_output_accuracy: 0.6579 - attrition_output_accuracy: 0.8466
Epoch 3/10
35/35 [==============================] - 0s 6ms/step - loss: 1.5258 - Department_output_loss: 0.9516 - attrition_output_loss: 0.5741 - Department_output_accuracy: 0.6579 - attrition_output_accuracy: 0.8466
Epoch 4/10
35/35 [==============================] - 0s 5ms/step - loss: 1.4478 - Department_output_loss: 0.8906 - attrition_output_loss: 0.5571 - Department_output_accuracy: 0.6579 - attrition_output_accuracy: 0.8466
Epoch 5/10
35/35 [==============================] - 0s 5ms/step - loss: 1.4070 - Department_output_loss: 0.8646 - attrition_output_l

In [76]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test, {'attrition_output' : y_attrition_test, 'Department_output' : y_department_test})

12/12 [==============================] - 0s 2ms/step - loss: 1.3290 - Department_output_loss: 0.8162 - attrition_output_loss: 0.5128 - Department_output_accuracy: 0.6413 - attrition_output_accuracy: 0.8152


In [78]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {test_results[3]}")
print(f"Attrition Accuracy: {test_results[4]}")


Department Accuracy: 0.6413043737411499
Attrition Accuracy: 0.8152173757553101


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy was the best metric to use for this data, because in this model the attrition accuracy was the highest metric.
2. I used the relu activation, because I thought the attrition and department would be nonlinear. Using relu allowed my model to work with nonlinear complex relationships.
3. This model could be improved by using more data. I also think not branching the department and attrition could be helpful. I think if we kept the department data in the X dataset then the attrition accuracy would increase.